### ISSUE TITLE
Make hardware slider optional?

### ISSUE THREAD

**Issue by luator** [open-dynamic-robot-initiative/solo#118]
Right now, one must have a slider box connected to the PC in order to be able to use Solo12.
Since I think for many applications the sliders are not needed, I'd like to make this optional.  The question is, what is the best way to do it from a configuration point of view.

Right now the behaviour is the following:
- A serial port is provided in the configuration.
- The `SerialReader` class first checks a number of hard-coded ports and only if this fails, it tries the one given in the documentation (thus the sliders are typically auto-detected and the config can be left empty).

If the sliders are configured to not be used, I would simply skip the initialisation of `SerialReader`  in `Solo12` and keep the slider-related fields in the senor data at zero.

But how to do it configuration-wise?  I currently see the following options:

- Option 1: Do not use the sliders if the serial port in the configuration is an empty string.  If one wants to use them and rely on auto-detection, one could put a value like "auto" (technically any other non-empty string would work as well).
  This seems to be the most intuitive solution to me, but would break existing configurations which happen to have the port set to an empty string.
- Option 2: Have a magic keyword (e.g. "disabled" or "none").  If the slider port is set to this value, the sliders are not used.
- Option 3: Add an additional value to the config, s.th. like "enable_sliders".

@MaximilienNaveau @thomasfla @jviereck  I currently tend to option 2.  What do you guys think?

**Comment by MaximilienNaveau** [comment]
I would vote for option 1 with the following change:
default empty string fall back to "auto".
Hence:

- if it's empty "" or "auto"
    -> do the automatic search and ignore not found, in any case log what happened and why ("user set the slider mode to "auto")
- if it's not empty
    -> assume that the user input a port for the slider and only try this one: exception on failure.

WDYT?

**Comment by luator** [comment]
After thinking a bit more about it, I would remove the "use if found, ignore if not"-case.  Either one wants to use the sliders, then the program should fail if they are not found.  Or one does not use them, then they should be disabled.  In either case it is IMO best if the user explicitly has to express the intend in the configuration.
Having an option where the sliders usually work but are silently ignored if they get disconnected sounds dangerous to me.

So my suggestion now would be:
- if port is empty ("") or "none": Do not use slider box.
- if port is "auto": Try to auto-detect, throw error if not found.
- else: Try to connect with the port given by the user, throw error if this fails.  Do not auto-detect.

Does that sound good?

@ahmadgazar @majidkhadiv FYI (and please add others if you think this discussion is relevant for them).

**Comment by MaximilienNaveau** [comment]
Yes I actually prefer the last solution, thanks @luator !
